# Generated by Django 4.1.3 on 2022-11-11 15:14

from django.db import migrations
import waggylabs.blocks.carousel
import waggylabs.blocks.label
import waggylabs.blocks.mathjax_markdown
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('waggylabs', '0002_alter_sitepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full subtitle', required=True)), ('blockquote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock(help_text='Quote text.', required=True, rows=3)), ('author', wagtail.blocks.CharBlock(help_text='Author of the quoted text.', required=False)), ('source', wagtail.blocks.CharBlock(help_text='Source of the quoted text.', required=False)), ('label', waggylabs.blocks.label.LabelBlock(max_length=50, required=False))])), ('pages', wagtail.blocks.PageChooserBlock(can_choose_root=True, required=True)), ('embed', wagtail.embeds.blocks.EmbedBlock(required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=True)), ('markdown', waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(icon='doc-full', required=True)), ('code', wagtail.blocks.StructBlock([('code', wagtail.blocks.StructBlock([('mode', wagtail.blocks.ChoiceBlock(choices=[('python', 'Python'), ('clike', 'C, C++, C#'), ('clike', 'Java'), ('javascript', 'Javascript'), ('xml', 'HTML, XML'), ('octave', 'MATLAB'), ('mathematica', 'Mathematica'), ('r', 'R'), ('clike', 'Kotlin'), ('swift', 'Swift'), ('powershell', 'Powershell'), ('sql', 'SQL'), ('css', 'CSS')], help_text='Choose the programming language.')), ('code', wagtail.blocks.TextBlock(help_text='Write or paste code.', required=True, rows=4))])), ('caption', waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(easymde_combine='true', easymde_max_height='150px', easymde_min_height='150px', easymde_toolbar_config='bold,italic,strikethrough,|,unordered-list,ordered-list,link,|,code,subscript,superscript,|,preview,side-by-side,fullscreen,guide', help_text='Listing caption', required=False)), ('label', waggylabs.blocks.label.LabelBlock(max_length=50, required=False))])), ('figure', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(help_text='Choose an image', required=True)), ('caption', waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(easymde_combine='true', easymde_max_height='150px', easymde_min_height='150px', easymde_toolbar_config='bold,italic,strikethrough,|,unordered-list,ordered-list,link,|,code,subscript,superscript,|,preview,side-by-side,fullscreen,guide', help_text='Figure caption', required=False)), ('label', waggylabs.blocks.label.LabelBlock(max_length=50, required=False))])), ('equation', wagtail.blocks.StructBlock([('equation', waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(easymde_combine='true', easymde_max_height='200px', easymde_min_height='200px', easymde_toolbar_config='subscript,superscript,equation,matrix,align,multiline,split,gather,alignat,flalign,|,preview,side-by-side,fullscreen', help_text='Write or paste LaTeX style equation (equation, matrix, align, etc. environments are supported).', required=True)), ('caption', waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(easymde_combine='true', easymde_max_height='150px', easymde_min_height='150px', easymde_toolbar_config='bold,italic,strikethrough,|,unordered-list,ordered-list,link,|,code,subscript,superscript,|,preview,side-by-side,fullscreen,guide', help_text='Equation caption that will be displayed when the equation is shown in the dialog box.', required=False)), ('label', waggylabs.blocks.label.LabelBlock(max_length=50, required=False))])), ('carousel', waggylabs.blocks.carousel.ImageCarouselBlock())], use_json_field=True),
        ),
    ]
