# Generated by Django 4.0.5 on 2022-08-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggylabs', '0003_alter_waggylabssettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waggylabssettings',
            name='navbar_placement',
            field=models.CharField(choices=[('', 'Default'), ('sticky-top', 'Sticky top'), ('fixed-top', 'Fixed top')], default='', help_text='Navigation bar placement options: default, sticky-top or fixed-top. See Bootstrap documentation.', max_length=10),
        ),
        migrations.AddField(
            model_name='waggylabssettings',
            name='navbar_theme',
            field=models.CharField(choices=[('navbar-light', 'Light'), ('navbar-dark', 'Dark')], default='navbar-light', help_text='Navigation bar theme: dark or light. Choice depends on the choice of the CSS Bootstrap theme.', max_length=12),
        ),
        migrations.AddField(
            model_name='waggylabssettings',
            name='site_theme',
            field=models.FileField(blank=True, help_text='CSS file with theme to be used instead of default Bootstrap theme. See Bootstrap documentation.', upload_to='', verbose_name='Bootstrap CSS theme'),
        ),
        migrations.AlterField(
            model_name='waggylabssettings',
            name='show_site_name',
            field=models.BooleanField(default=True, help_text='Indicates if title of the Waggy Labs site appears in navigation bar and in browser tab e.g., Page Title - Site Name.', verbose_name='Show site name in navigation bar and browser tab'),
        ),
    ]
