# Generated by Django 4.1.3 on 2023-01-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggylabs', '0003_navbar_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waggylabssettings',
            name='navbar_color',
            field=models.CharField(blank=True, default='rgba(33, 37, 41, 0.5)', help_text='Choose a specific color and opacity for the navigation bar. The color does not work if navigation bar color mode is selected to be Auto.', max_length=25),
        ),
    ]
