# Generated by Django 4.1.3 on 2023-01-16 19:40

from django.db import migrations, models
import waggylabs.blocks.links
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("waggylabs", "0004_navbar_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="waggylabssettings",
            name="navbar_links",
            field=wagtail.fields.StreamField(
                [
                    (
                        "external_link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "link",
                                    wagtail.blocks.URLBlock(
                                        label="Link to external site", required=True
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        label="Text of the link", required=False
                                    ),
                                ),
                                (
                                    "icon",
                                    waggylabs.blocks.links.IconBlock(label="Icon"),
                                ),
                                (
                                    "style",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Choose style"),
                                            ("btn btn-primary", "Button primary"),
                                            ("btn btn-secondary", "Button secondary"),
                                            ("btn btn-success", "Button success"),
                                            ("btn btn-danger", "Button danger"),
                                            ("btn btn-warning", "Button warning"),
                                            ("btn btn-info", "Button info"),
                                            (
                                                "btn btn-outline-primary",
                                                "Button outline primary",
                                            ),
                                            (
                                                "btn btn-outline-secondary",
                                                "Button outline secondary",
                                            ),
                                            (
                                                "btn btn-outline-success",
                                                "Button outline success",
                                            ),
                                            (
                                                "btn btn-outline-danger",
                                                "Button outline danger",
                                            ),
                                            (
                                                "btn btn-outline-warning",
                                                "Button outline warning",
                                            ),
                                            (
                                                "btn btn-outline-info",
                                                "Button outline info",
                                            ),
                                            ("card-link", "Link"),
                                        ],
                                        label="Style of the link",
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "internal_link",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "link",
                                    wagtail.blocks.PageChooserBlock(
                                        label="Link to a page of this site"
                                    ),
                                ),
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(
                                        label="Text instead of page title",
                                        required=False,
                                    ),
                                ),
                                (
                                    "icon",
                                    waggylabs.blocks.links.IconBlock(label="Icon"),
                                ),
                                (
                                    "style",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Choose style"),
                                            ("btn btn-primary", "Button primary"),
                                            ("btn btn-secondary", "Button secondary"),
                                            ("btn btn-success", "Button success"),
                                            ("btn btn-danger", "Button danger"),
                                            ("btn btn-warning", "Button warning"),
                                            ("btn btn-info", "Button info"),
                                            (
                                                "btn btn-outline-primary",
                                                "Button outline primary",
                                            ),
                                            (
                                                "btn btn-outline-secondary",
                                                "Button outline secondary",
                                            ),
                                            (
                                                "btn btn-outline-success",
                                                "Button outline success",
                                            ),
                                            (
                                                "btn btn-outline-danger",
                                                "Button outline danger",
                                            ),
                                            (
                                                "btn btn-outline-warning",
                                                "Button outline warning",
                                            ),
                                            (
                                                "btn btn-outline-info",
                                                "Button outline info",
                                            ),
                                            ("card-link", "Link"),
                                        ],
                                        label="Style of the link",
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="waggylabssettings",
            name="navbar_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Choose a specific color and opacity for the navigation bar. The color does not work if navigation bar color mode is selected to be Auto.",
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="waggylabssettings",
            name="navbar_theme",
            field=models.CharField(
                blank=True,
                choices=[("", "Auto"), ("light", "Light"), ("dark", "Dark")],
                default="",
                help_text="Navigation bar color mode: auto, light or dark. Auto mode changes according to the global color mode selection. Light or dark mode keep the selected mode, especially useful if CSS does not support color modes, or specific color for the navigation bar was selected. Ignored if the uploaded CSS does not support color modes.",
                max_length=25,
                verbose_name="Navigation bar color mode",
            ),
        ),
    ]
