# Generated by Django 4.0.5 on 2022-08-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggylabs', '0004_waggylabssettings_navbar_placement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waggylabssettings',
            name='navbar_theme',
            field=models.CharField(choices=[('navbar-light bg-light', 'Light'), ('navbar-dark bg-dark', 'Dark')], default='navbar-light bg-light', help_text='Navigation bar theme: dark or light. Choice depends on the choice of the CSS Bootstrap theme.', max_length=25),
        ),
    ]
