# Generated by Django 4.0.5 on 2022-08-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggylabs', '0006_alter_waggylabssettings_navbar_placement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waggylabssettings',
            name='navbar_menu_alignment',
            field=models.CharField(blank=True, choices=[('', 'Left'), ('ms-md-auto', 'Right')], default='', help_text='Menu links alignment in the navigation bar.', max_length=10),
        ),
    ]
