# Generated by Django 4.1.3 on 2023-01-22 11:24

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("waggylabs", "0007_footer_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitepage",
            name="sidebar",
            field=wagtail.fields.StreamField(
                [
                    (
                        "table_of_contents",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title to appear on the tab.",
                                        label="Title",
                                        required=True,
                                    ),
                                )
                            ]
                        ),
                    ),
                    (
                        "visuals",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title to appear on the tab.",
                                        label="Title",
                                        required=True,
                                    ),
                                ),
                                (
                                    "include_embeds",
                                    wagtail.blocks.BooleanBlock(
                                        label="Include embeds", required=False
                                    ),
                                ),
                                (
                                    "include_equations",
                                    wagtail.blocks.BooleanBlock(
                                        label="Include equations", required=False
                                    ),
                                ),
                                (
                                    "include_figures",
                                    wagtail.blocks.BooleanBlock(
                                        label="Include figures", required=False
                                    ),
                                ),
                                (
                                    "include_listings",
                                    wagtail.blocks.BooleanBlock(
                                        label="Include listings", required=False
                                    ),
                                ),
                                (
                                    "include_tables",
                                    wagtail.blocks.BooleanBlock(
                                        label="Include tables", required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "citations",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "title",
                                    wagtail.blocks.CharBlock(
                                        help_text="Title to appear on the tab.",
                                        label="Title",
                                        required=True,
                                    ),
                                )
                            ]
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="waggylabssettings",
            name="site_icon",
            field=models.ForeignKey(
                blank=True,
                help_text="Brand icon that appears in navigation bar and in the browser tab.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Site icon",
            ),
        ),
    ]
