# Generated by Django 4.0.5 on 2022-08-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggylabs', '0008_alter_waggylabssettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='waggylabssettings',
            name='show_social_names',
            field=models.BooleanField(default=True, help_text='Choose if social site name should be displayed instead of account name for the social links.', verbose_name='Show social names instead of account'),
        ),
    ]
