# Generated by Django 4.1.3 on 2023-01-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggylabs', '0009_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitepage',
            name='show_sidebar',
            field=models.BooleanField(blank=True, default=False, help_text='Controls the appearance of sidebar. Needed to keep the sidebar settings but keep it hidden.', verbose_name='Show sidebar'),
        ),
    ]
