# Generated by Django 4.1.3 on 2023-01-23 11:29

from django.db import migrations
import waggylabs.blocks.icon
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('waggylabs', '0010_sidebar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='sidebar',
            field=wagtail.fields.StreamField([('sidebar', wagtail.blocks.StructBlock([('tabs_style', wagtail.blocks.ChoiceBlock(choices=[('', 'Choose tabs style'), ('nav nav-tabs', 'Tabs'), ('nav nav-pills', 'Pills'), ('nav nav-pills nav-fill', 'Wide pills')], label='Tabs style')), ('tabs_justify', wagtail.blocks.ChoiceBlock(choices=[('', 'Choose horizontal alignment'), ('justify-content-start', 'Align left'), ('justify-content-center', 'Align center'), ('justify-content-end', 'Align right')], label='Tabs orientation')), ('tabs_orientation', wagtail.blocks.ChoiceBlock(choices=[('', 'Choose orientation'), ('horizontal', 'Horizontal'), ('vertical', 'Vertical')], label='Tabs orientation')), ('items', wagtail.blocks.StreamBlock([('table_of_contents', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title to appear on the tab.', label='Title', required=False)), ('icon', waggylabs.blocks.icon.IconBlock(label='Icon', required=False))])), ('visuals', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title to appear on the tab.', label='Title', required=False)), ('icon', waggylabs.blocks.icon.IconBlock(label='Icon', required=False)), ('include_embeds', wagtail.blocks.BooleanBlock(label='Include embeds', required=False)), ('include_equations', wagtail.blocks.BooleanBlock(label='Include equations', required=False)), ('include_figures', wagtail.blocks.BooleanBlock(label='Include figures', required=False)), ('include_listings', wagtail.blocks.BooleanBlock(label='Include listings', required=False)), ('include_tables', wagtail.blocks.BooleanBlock(label='Include tables', required=False))])), ('citations', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(help_text='Title to appear on the tab.', label='Title', required=False)), ('icon', waggylabs.blocks.icon.IconBlock(label='Icon', required=False))]))]))]))], blank=True, use_json_field=True),
        ),
    ]
