# Generated by Django 4.0.5 on 2022-08-06 21:38

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('waggylabs', '0010_remove_waggylabssettings_github_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waggylabssettingssociallinks',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='waggylabs.waggylabssettings'),
        ),
    ]
