# Generated by Django 4.1.6 on 2023-02-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waggylabs", "0015_sidebar"),
    ]

    operations = [
        migrations.AddField(
            model_name="waggylabssettings",
            name="constant_content_width",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Keep the width of the page content always the same indepent from presence or absence of sidebar on the page. If true, when the sidebar is not present on the page, its place stays empty without change of page content width.",
                verbose_name="Keep content width constant",
            ),
        ),
    ]
