# Generated by Django 4.0.5 on 2022-08-28 22:20

from django.db import migrations
import waggylabs.blocks.mathjax_markdown
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('waggylabs', '0016_alter_sitepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full subtitle', required=True)), ('paragraph', wagtail.blocks.RichTextBlock(required=True)), ('blockquote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock(help_text='Quote text.', required=True, rows=3)), ('author', wagtail.blocks.CharBlock(help_text='Author of the quoted text.', required=False)), ('source', wagtail.blocks.CharBlock(help_text='Source of the quoted text.', required=False))])), ('pages', wagtail.blocks.PageChooserBlock(can_choose_root=True, required=True)), ('embed', wagtail.embeds.blocks.EmbedBlock(required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=True)), ('markdown', waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(icon='code', required=True))], use_json_field=True),
        ),
    ]
