# Generated by Django 4.1.3 on 2022-12-05 22:15

from django.db import migrations
import waggylabs.blocks.carousel
import waggylabs.blocks.label
import waggylabs.blocks.links
import waggylabs.blocks.mathjax_markdown
import waggylabs.blocks.table
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("waggylabs", "0016_alter_sitepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.CharBlock(
                            form_classname="full subtitle", required=True
                        ),
                    ),
                    (
                        "blockquote",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "quote",
                                    wagtail.blocks.TextBlock(
                                        label="Quote text.", required=True, rows=3
                                    ),
                                ),
                                (
                                    "author",
                                    wagtail.blocks.CharBlock(
                                        label="Author of the quoted text.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "source",
                                    wagtail.blocks.CharBlock(
                                        label="Source of the quoted text.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "label",
                                    waggylabs.blocks.label.LabelBlock(
                                        form_classname="waggylabs-label-blockquote",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "pages",
                        wagtail.blocks.PageChooserBlock(
                            can_choose_root=True, required=True
                        ),
                    ),
                    ("embed", wagtail.embeds.blocks.EmbedBlock(required=True)),
                    (
                        "document",
                        wagtail.documents.blocks.DocumentChooserBlock(required=True),
                    ),
                    (
                        "markdown",
                        waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                            icon="doc-full", required=True
                        ),
                    ),
                    (
                        "code",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "code",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "mode",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("python", "Python"),
                                                        ("clike", "C, C++, C#"),
                                                        ("clike", "Java"),
                                                        ("javascript", "Javascript"),
                                                        ("xml", "HTML, XML"),
                                                        ("octave", "MATLAB"),
                                                        ("mathematica", "Mathematica"),
                                                        ("r", "R"),
                                                        ("clike", "Kotlin"),
                                                        ("swift", "Swift"),
                                                        ("powershell", "Powershell"),
                                                        ("sql", "SQL"),
                                                        ("css", "CSS"),
                                                    ],
                                                    label="Code language",
                                                ),
                                            ),
                                            (
                                                "code",
                                                wagtail.blocks.TextBlock(
                                                    label="Code snippet",
                                                    required=True,
                                                    rows=4,
                                                ),
                                            ),
                                        ],
                                        label=None,
                                    ),
                                ),
                                (
                                    "caption",
                                    waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                                        easymde_combine="true",
                                        easymde_max_height="100px",
                                        easymde_min_height="100px",
                                        easymde_status="false",
                                        easymde_toolbar_config="bold,italic,strikethrough,|,unordered-list,ordered-list,link,|,code,subscript,superscript,|,preview,side-by-side,fullscreen,guide",
                                        help_text=None,
                                        label="Listing caption",
                                        required=False,
                                    ),
                                ),
                                (
                                    "label",
                                    waggylabs.blocks.label.LabelBlock(
                                        form_classname="waggylabs-label-listing",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "figure",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Graphic", required=True
                                    ),
                                ),
                                (
                                    "caption",
                                    waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                                        easymde_combine="true",
                                        easymde_max_height="100px",
                                        easymde_min_height="100px",
                                        easymde_status="false",
                                        easymde_toolbar_config="bold,italic,strikethrough,|,unordered-list,ordered-list,link,|,code,subscript,superscript,|,preview,side-by-side,fullscreen,guide",
                                        help_text=None,
                                        label="Figure caption",
                                        required=False,
                                    ),
                                ),
                                (
                                    "label",
                                    waggylabs.blocks.label.LabelBlock(
                                        form_classname="waggylabs-label-figure",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "equation",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "equation",
                                    waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                                        easymde_combine="true",
                                        easymde_max_height="150px",
                                        easymde_min_height="150px",
                                        easymde_status="false",
                                        easymde_toolbar_config="subscript,superscript,equation,matrix,align,multiline,split,gather,alignat,flalign,|,preview,side-by-side,fullscreen",
                                        help_text="Write or paste LaTeX style equation (equation, matrix, align, etc. environments are supported).",
                                        required=True,
                                    ),
                                ),
                                (
                                    "caption",
                                    waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                                        easymde_combine="true",
                                        easymde_max_height="100px",
                                        easymde_min_height="100px",
                                        easymde_status="false",
                                        easymde_toolbar_config="bold,italic,strikethrough,|,unordered-list,ordered-list,link,|,code,subscript,superscript,|,preview,side-by-side,fullscreen,guide",
                                        help_text=None,
                                        label="Equation caption",
                                        required=False,
                                    ),
                                ),
                                (
                                    "label",
                                    waggylabs.blocks.label.LabelBlock(
                                        max_length=50, required=False
                                    ),
                                ),
                            ]
                        ),
                    ),
                    ("carousel", waggylabs.blocks.carousel.ImageCarouselBlock()),
                    (
                        "table_figure",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "caption",
                                    waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                                        easymde_combine="true",
                                        easymde_max_height="150px",
                                        easymde_min_height="150px",
                                        easymde_status="false",
                                        easymde_toolbar_config="bold,italic,strikethrough,|,unordered-list,ordered-list,link,|,code,subscript,superscript,|,preview,side-by-side,fullscreen,guide",
                                        help_text=None,
                                        label="Table caption",
                                        required=False,
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Table image", required=True
                                    ),
                                ),
                                (
                                    "footer",
                                    waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                                        easymde_combine="true",
                                        easymde_max_height="100px",
                                        easymde_min_height="100px",
                                        easymde_status="false",
                                        easymde_toolbar_config="bold,italic,strikethrough,|,unordered-list,ordered-list,link,|,code,subscript,superscript,|,preview,side-by-side,fullscreen,guide",
                                        help_text=None,
                                        label="Table footer",
                                        required=False,
                                    ),
                                ),
                                (
                                    "label",
                                    waggylabs.blocks.label.LabelBlock(
                                        form_classname="waggylabs-label-table",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "table",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "caption",
                                    waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                                        easymde_combine="true",
                                        easymde_max_height="100px",
                                        easymde_min_height="100px",
                                        easymde_status="false",
                                        easymde_toolbar_config="bold,italic,strikethrough,|,unordered-list,ordered-list,link,|,code,subscript,superscript,|,preview,side-by-side,fullscreen,guide",
                                        help_text=None,
                                        label="Table caption",
                                        required=False,
                                    ),
                                ),
                                (
                                    "table",
                                    waggylabs.blocks.table.BareTableBlock(
                                        help_text="Columns and rows can be added via context menu appearing on the right click. Markdown inside cells is supported. Inline LateX equations can be added using $...$ pattern.",
                                        keep_table_tag=False,
                                        label="Table data",
                                        required=True,
                                    ),
                                ),
                                (
                                    "footer",
                                    waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                                        easymde_combine="true",
                                        easymde_max_height="100px",
                                        easymde_min_height="100px",
                                        easymde_status="false",
                                        easymde_toolbar_config="bold,italic,strikethrough,|,unordered-list,ordered-list,link,|,code,subscript,superscript,|,preview,side-by-side,fullscreen,guide",
                                        help_text=None,
                                        label="Table footer",
                                        required=False,
                                    ),
                                ),
                                (
                                    "label",
                                    waggylabs.blocks.label.LabelBlock(
                                        form_classname="waggylabs-label-table",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "accordion",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "style",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Choose item collapse style"),
                                            ("collapsible", "Items collapse"),
                                            ("stays_open", "Items stay open"),
                                        ],
                                        label="Collapse items when new items opens or keep them open",
                                    ),
                                ),
                                (
                                    "items",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "heading",
                                                    wagtail.blocks.CharBlock(
                                                        form_classname="full subtitle",
                                                        label="Item Heading",
                                                        required=True,
                                                    ),
                                                ),
                                                (
                                                    "is_open",
                                                    wagtail.blocks.BooleanBlock(
                                                        label="Is open", required=False
                                                    ),
                                                ),
                                                (
                                                    "body",
                                                    wagtail.blocks.StreamBlock(
                                                        [
                                                            (
                                                                "markdown",
                                                                waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                                                                    easymde_combine="true",
                                                                    easymde_max_height="150px",
                                                                    easymde_min_height="150px",
                                                                    easymde_status="false",
                                                                    easymde_toolbar_config="bold,italic,strikethrough,|,unordered-list,ordered-list,link,|,code,subscript,superscript,|,preview,side-by-side,fullscreen,guide",
                                                                    help_text="",
                                                                    required=False,
                                                                ),
                                                            ),
                                                            (
                                                                "code",
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "code",
                                                                            wagtail.blocks.StructBlock(
                                                                                [
                                                                                    (
                                                                                        "mode",
                                                                                        wagtail.blocks.ChoiceBlock(
                                                                                            choices=[
                                                                                                (
                                                                                                    "python",
                                                                                                    "Python",
                                                                                                ),
                                                                                                (
                                                                                                    "clike",
                                                                                                    "C, C++, C#",
                                                                                                ),
                                                                                                (
                                                                                                    "clike",
                                                                                                    "Java",
                                                                                                ),
                                                                                                (
                                                                                                    "javascript",
                                                                                                    "Javascript",
                                                                                                ),
                                                                                                (
                                                                                                    "xml",
                                                                                                    "HTML, XML",
                                                                                                ),
                                                                                                (
                                                                                                    "octave",
                                                                                                    "MATLAB",
                                                                                                ),
                                                                                                (
                                                                                                    "mathematica",
                                                                                                    "Mathematica",
                                                                                                ),
                                                                                                (
                                                                                                    "r",
                                                                                                    "R",
                                                                                                ),
                                                                                                (
                                                                                                    "clike",
                                                                                                    "Kotlin",
                                                                                                ),
                                                                                                (
                                                                                                    "swift",
                                                                                                    "Swift",
                                                                                                ),
                                                                                                (
                                                                                                    "powershell",
                                                                                                    "Powershell",
                                                                                                ),
                                                                                                (
                                                                                                    "sql",
                                                                                                    "SQL",
                                                                                                ),
                                                                                                (
                                                                                                    "css",
                                                                                                    "CSS",
                                                                                                ),
                                                                                            ],
                                                                                            label="Code language",
                                                                                        ),
                                                                                    ),
                                                                                    (
                                                                                        "code",
                                                                                        wagtail.blocks.TextBlock(
                                                                                            label="Code snippet",
                                                                                            required=True,
                                                                                            rows=4,
                                                                                        ),
                                                                                    ),
                                                                                ],
                                                                                label=None,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "caption",
                                                                            waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                                                                                easymde_combine="true",
                                                                                easymde_max_height="100px",
                                                                                easymde_min_height="100px",
                                                                                easymde_status="false",
                                                                                easymde_toolbar_config="bold,italic,strikethrough,|,unordered-list,ordered-list,link,|,code,subscript,superscript,|,preview,side-by-side,fullscreen,guide",
                                                                                help_text=None,
                                                                                label="Listing caption",
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "label",
                                                                            waggylabs.blocks.label.LabelBlock(
                                                                                form_classname="waggylabs-label-listing",
                                                                                max_length=50,
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                    ]
                                                                ),
                                                            ),
                                                            (
                                                                "figure",
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "image",
                                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                                label="Graphic",
                                                                                required=True,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "caption",
                                                                            waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                                                                                easymde_combine="true",
                                                                                easymde_max_height="100px",
                                                                                easymde_min_height="100px",
                                                                                easymde_status="false",
                                                                                easymde_toolbar_config="bold,italic,strikethrough,|,unordered-list,ordered-list,link,|,code,subscript,superscript,|,preview,side-by-side,fullscreen,guide",
                                                                                help_text=None,
                                                                                label="Figure caption",
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "label",
                                                                            waggylabs.blocks.label.LabelBlock(
                                                                                form_classname="waggylabs-label-figure",
                                                                                max_length=50,
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                    ]
                                                                ),
                                                            ),
                                                            (
                                                                "embed",
                                                                wagtail.embeds.blocks.EmbedBlock(
                                                                    required=True
                                                                ),
                                                            ),
                                                            (
                                                                "equation",
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "equation",
                                                                            waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                                                                                easymde_combine="true",
                                                                                easymde_max_height="150px",
                                                                                easymde_min_height="150px",
                                                                                easymde_status="false",
                                                                                easymde_toolbar_config="subscript,superscript,equation,matrix,align,multiline,split,gather,alignat,flalign,|,preview,side-by-side,fullscreen",
                                                                                help_text="Write or paste LaTeX style equation (equation, matrix, align, etc. environments are supported).",
                                                                                required=True,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "caption",
                                                                            waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                                                                                easymde_combine="true",
                                                                                easymde_max_height="100px",
                                                                                easymde_min_height="100px",
                                                                                easymde_status="false",
                                                                                easymde_toolbar_config="bold,italic,strikethrough,|,unordered-list,ordered-list,link,|,code,subscript,superscript,|,preview,side-by-side,fullscreen,guide",
                                                                                help_text=None,
                                                                                label="Equation caption",
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "label",
                                                                            waggylabs.blocks.label.LabelBlock(
                                                                                max_length=50,
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                    ]
                                                                ),
                                                            ),
                                                            (
                                                                "table_figure",
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "caption",
                                                                            waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                                                                                easymde_combine="true",
                                                                                easymde_max_height="150px",
                                                                                easymde_min_height="150px",
                                                                                easymde_status="false",
                                                                                easymde_toolbar_config="bold,italic,strikethrough,|,unordered-list,ordered-list,link,|,code,subscript,superscript,|,preview,side-by-side,fullscreen,guide",
                                                                                help_text=None,
                                                                                label="Table caption",
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "image",
                                                                            wagtail.images.blocks.ImageChooserBlock(
                                                                                label="Table image",
                                                                                required=True,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "footer",
                                                                            waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                                                                                easymde_combine="true",
                                                                                easymde_max_height="100px",
                                                                                easymde_min_height="100px",
                                                                                easymde_status="false",
                                                                                easymde_toolbar_config="bold,italic,strikethrough,|,unordered-list,ordered-list,link,|,code,subscript,superscript,|,preview,side-by-side,fullscreen,guide",
                                                                                help_text=None,
                                                                                label="Table footer",
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "label",
                                                                            waggylabs.blocks.label.LabelBlock(
                                                                                form_classname="waggylabs-label-table",
                                                                                max_length=50,
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                    ]
                                                                ),
                                                            ),
                                                            (
                                                                "table",
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "caption",
                                                                            waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                                                                                easymde_combine="true",
                                                                                easymde_max_height="100px",
                                                                                easymde_min_height="100px",
                                                                                easymde_status="false",
                                                                                easymde_toolbar_config="bold,italic,strikethrough,|,unordered-list,ordered-list,link,|,code,subscript,superscript,|,preview,side-by-side,fullscreen,guide",
                                                                                help_text=None,
                                                                                label="Table caption",
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "table",
                                                                            waggylabs.blocks.table.BareTableBlock(
                                                                                help_text="Columns and rows can be added via context menu appearing on the right click. Markdown inside cells is supported. Inline LateX equations can be added using $...$ pattern.",
                                                                                keep_table_tag=False,
                                                                                label="Table data",
                                                                                required=True,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "footer",
                                                                            waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                                                                                easymde_combine="true",
                                                                                easymde_max_height="100px",
                                                                                easymde_min_height="100px",
                                                                                easymde_status="false",
                                                                                easymde_toolbar_config="bold,italic,strikethrough,|,unordered-list,ordered-list,link,|,code,subscript,superscript,|,preview,side-by-side,fullscreen,guide",
                                                                                help_text=None,
                                                                                label="Table footer",
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "label",
                                                                            waggylabs.blocks.label.LabelBlock(
                                                                                form_classname="waggylabs-label-table",
                                                                                max_length=50,
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                    ]
                                                                ),
                                                            ),
                                                        ],
                                                        required=True,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "card_grid",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "height_style",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Choose height style"),
                                            ("equal", "Equal height"),
                                            ("not_equal", "Height wraps to content"),
                                        ],
                                        label="Height",
                                    ),
                                ),
                                (
                                    "grouping_style",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Choose grouping style"),
                                            ("separate", "Separate"),
                                            ("grouped", "Grouped"),
                                        ],
                                        label="Grouping",
                                    ),
                                ),
                                (
                                    "orientation_style",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Choose orientation"),
                                            ("vertical", "Vertical"),
                                            ("horizontal", "Horizontal"),
                                        ],
                                        label="Orientation",
                                    ),
                                ),
                                (
                                    "columns",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Choose columns"),
                                            (1, "1 column"),
                                            (2, "2 columns"),
                                            (3, "3 columns"),
                                            (4, "4 columns"),
                                            (5, "5 columns"),
                                        ],
                                        label="Number of columns",
                                    ),
                                ),
                                (
                                    "cards",
                                    wagtail.blocks.ListBlock(
                                        wagtail.blocks.StructBlock(
                                            [
                                                (
                                                    "image",
                                                    wagtail.images.blocks.ImageChooserBlock(
                                                        label="Image", required=False
                                                    ),
                                                ),
                                                (
                                                    "title",
                                                    wagtail.blocks.CharBlock(
                                                        label="Title", required=True
                                                    ),
                                                ),
                                                (
                                                    "subtitle",
                                                    wagtail.blocks.CharBlock(
                                                        label="Subtitle", required=False
                                                    ),
                                                ),
                                                (
                                                    "text",
                                                    waggylabs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                                                        easymde_combine="true",
                                                        easymde_max_height="100px",
                                                        easymde_min_height="100px",
                                                        easymde_status="false",
                                                        easymde_toolbar_config="bold,italic,strikethrough,|,unordered-list,ordered-list,link,|,code,subscript,superscript,|,preview,side-by-side,fullscreen,guide",
                                                        help_text=None,
                                                        required=False,
                                                    ),
                                                ),
                                                (
                                                    "links",
                                                    wagtail.blocks.StreamBlock(
                                                        [
                                                            (
                                                                "external_link",
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "link",
                                                                            wagtail.blocks.URLBlock(
                                                                                label="Link to external site",
                                                                                required=True,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "text",
                                                                            wagtail.blocks.CharBlock(
                                                                                label="Text of the link",
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "icon",
                                                                            waggylabs.blocks.links.IconBlock(
                                                                                label="Icon"
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "style",
                                                                            wagtail.blocks.ChoiceBlock(
                                                                                choices=[
                                                                                    (
                                                                                        "",
                                                                                        "Choose style",
                                                                                    ),
                                                                                    (
                                                                                        "btn btn-primary",
                                                                                        "Button",
                                                                                    ),
                                                                                    (
                                                                                        "card-link",
                                                                                        "Link",
                                                                                    ),
                                                                                ],
                                                                                label="Style of the link",
                                                                            ),
                                                                        ),
                                                                    ]
                                                                ),
                                                            ),
                                                            (
                                                                "internal_link",
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "link",
                                                                            wagtail.blocks.PageChooserBlock(
                                                                                label="Link to a page of this site"
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "text",
                                                                            wagtail.blocks.CharBlock(
                                                                                label="Text instead of page title",
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "icon",
                                                                            waggylabs.blocks.links.IconBlock(
                                                                                label="Icon"
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "style",
                                                                            wagtail.blocks.ChoiceBlock(
                                                                                choices=[
                                                                                    (
                                                                                        "",
                                                                                        "Choose style",
                                                                                    ),
                                                                                    (
                                                                                        "btn btn-primary",
                                                                                        "Button",
                                                                                    ),
                                                                                    (
                                                                                        "card-link",
                                                                                        "Link",
                                                                                    ),
                                                                                ],
                                                                                label="Style of the link",
                                                                            ),
                                                                        ),
                                                                    ]
                                                                ),
                                                            ),
                                                            (
                                                                "email",
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "email",
                                                                            wagtail.blocks.EmailBlock(
                                                                                label="Email address",
                                                                                required=True,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "text",
                                                                            wagtail.blocks.CharBlock(
                                                                                label="Text to be displayed instead of address",
                                                                                required=False,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "icon",
                                                                            waggylabs.blocks.links.IconBlock(
                                                                                required=False
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "style",
                                                                            wagtail.blocks.ChoiceBlock(
                                                                                choices=[
                                                                                    (
                                                                                        "",
                                                                                        "Choose style",
                                                                                    ),
                                                                                    (
                                                                                        "btn btn-primary",
                                                                                        "Button",
                                                                                    ),
                                                                                    (
                                                                                        "card-link",
                                                                                        "Link",
                                                                                    ),
                                                                                ],
                                                                                label="Style of the link",
                                                                            ),
                                                                        ),
                                                                    ]
                                                                ),
                                                            ),
                                                            (
                                                                "info_text",
                                                                wagtail.blocks.StructBlock(
                                                                    [
                                                                        (
                                                                            "text",
                                                                            wagtail.blocks.CharBlock(
                                                                                label="Phone, address, etc.",
                                                                                required=True,
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "icon",
                                                                            waggylabs.blocks.links.IconBlock(
                                                                                required=False
                                                                            ),
                                                                        ),
                                                                        (
                                                                            "style",
                                                                            wagtail.blocks.ChoiceBlock(
                                                                                choices=[
                                                                                    (
                                                                                        "",
                                                                                        "Choose style",
                                                                                    ),
                                                                                    (
                                                                                        "btn btn-primary",
                                                                                        "Button",
                                                                                    ),
                                                                                    (
                                                                                        "card-link",
                                                                                        "Link",
                                                                                    ),
                                                                                ],
                                                                                label="Style of the link",
                                                                            ),
                                                                        ),
                                                                    ]
                                                                ),
                                                            ),
                                                        ],
                                                        required=False,
                                                    ),
                                                ),
                                            ]
                                        )
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
