# Generated by Django 4.1.6 on 2023-03-25 20:03

from django.db import migrations
import waggylabs.blocks.icon
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("waggylabs", "0038_footer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="waggylabssettings",
            name="footer",
            field=wagtail.fields.StreamField(
                [
                    (
                        "post_highlights",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "header",
                                    wagtail.blocks.CharBlock(
                                        label="Header text", required=False
                                    ),
                                ),
                                (
                                    "header_icon",
                                    waggylabs.blocks.icon.IconBlock(
                                        label="Header icon", required=False
                                    ),
                                ),
                                (
                                    "header_icon_location",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "Before text"),
                                            ("end", "After text"),
                                        ],
                                        label="Header icon location",
                                        required=False,
                                    ),
                                ),
                                (
                                    "col_offset",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("", "No offset"),
                                            ("offset-lg-1", "Narrow"),
                                            ("offset-lg-2", "Medium"),
                                            ("offset-lg-3", "Wide"),
                                        ],
                                        label="Offset",
                                        required=False,
                                    ),
                                ),
                                (
                                    "col_width",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("col-lg-2", "Narrow"),
                                            ("col-lg-3", "Medium"),
                                            ("col-lg-4", "Wide"),
                                        ],
                                        label="Width",
                                    ),
                                ),
                                (
                                    "item",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "post_list_page",
                                                wagtail.blocks.PageChooserBlock(
                                                    help_text="Shows only posts that are descendant of this page. If left empty, posts selected from all the posts are shown.",
                                                    label="Root post list page",
                                                    page_type=[
                                                        "waggylabs.PostListPage"
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "posts_style",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("", "Default list"),
                                                        (
                                                            "list-unstyled",
                                                            "Unstyled list",
                                                        ),
                                                        (
                                                            "list-numbered",
                                                            "Numbered list",
                                                        ),
                                                        ("list-group", "List group"),
                                                        (
                                                            "list-group list-group-flush",
                                                            "List group, no outer borders",
                                                        ),
                                                        (
                                                            "list-group list-group-numbered",
                                                            "Numbered list group",
                                                        ),
                                                        (
                                                            "list-group list-group-numbered list-group-flush",
                                                            "Numbered list group, no outer borders",
                                                        ),
                                                    ],
                                                    label="Post list style",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "posts_number",
                                                wagtail.blocks.IntegerBlock(
                                                    help_text="If zero, all post are shown.",
                                                    label="Number of posts to show",
                                                    min_value=0,
                                                    required=True,
                                                ),
                                            ),
                                            (
                                                "post_style",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("", "Default list item"),
                                                        (
                                                            "list-group-item list-group-item-action",
                                                            "List group item",
                                                        ),
                                                        (
                                                            "list-group-item list-group-item-action list-group-item-primary",
                                                            "List group item primary",
                                                        ),
                                                        (
                                                            "list-group-item list-group-item-action list-group-item-secondary",
                                                            "List group item secondary",
                                                        ),
                                                        (
                                                            "list-group-item list-group-item-action list-group-item-success",
                                                            "List group item success",
                                                        ),
                                                        (
                                                            "list-group-item list-group-item-action list-group-item-danger",
                                                            "List group item danger",
                                                        ),
                                                        (
                                                            "list-group-item list-group-item-action list-group-item-warning",
                                                            "List group item warning",
                                                        ),
                                                        (
                                                            "list-group-item list-group-item-action list-group-item-info",
                                                            "List group item info",
                                                        ),
                                                        (
                                                            "list-group-item list-group-item-action list-group-item-light",
                                                            "List group item light",
                                                        ),
                                                        (
                                                            "list-group-item list-group-item-action list-group-item-dark",
                                                            "List group item dark",
                                                        ),
                                                        (
                                                            "btn btn-primary",
                                                            "Button primary",
                                                        ),
                                                        (
                                                            "btn btn-secondary",
                                                            "Button secondary",
                                                        ),
                                                        (
                                                            "btn btn-success",
                                                            "Button success",
                                                        ),
                                                        (
                                                            "btn btn-danger",
                                                            "Button danger",
                                                        ),
                                                        (
                                                            "btn btn-warning",
                                                            "Button warning",
                                                        ),
                                                        ("btn btn-info", "Button info"),
                                                        (
                                                            "btn btn-outline-primary",
                                                            "Button outline primary",
                                                        ),
                                                        (
                                                            "btn btn-outline-secondary",
                                                            "Button outline secondary",
                                                        ),
                                                        (
                                                            "btn btn-outline-success",
                                                            "Button outline success",
                                                        ),
                                                        (
                                                            "btn btn-outline-danger",
                                                            "Button outline danger",
                                                        ),
                                                        (
                                                            "btn btn-outline-warning",
                                                            "Button outline warning",
                                                        ),
                                                        (
                                                            "btn btn-outline-info",
                                                            "Button outline info",
                                                        ),
                                                        ("card-link", "Card link"),
                                                        (
                                                            "nav-link",
                                                            "Navigation bar link",
                                                        ),
                                                        (
                                                            "nav-link active",
                                                            "Navigation bar active link",
                                                        ),
                                                        (
                                                            "link-primary",
                                                            "Primary link",
                                                        ),
                                                        (
                                                            "link-secondary",
                                                            "Secondary link",
                                                        ),
                                                        (
                                                            "link-success",
                                                            "Success link",
                                                        ),
                                                        ("link-danger", "Danger link"),
                                                        (
                                                            "link-warning",
                                                            "Warning link",
                                                        ),
                                                        ("link-info", "Info link"),
                                                        ("link-light", "Light link"),
                                                        ("link-dark", "Dark link"),
                                                        (
                                                            "nav-link link-primary",
                                                            "Primary link, no underline",
                                                        ),
                                                        (
                                                            "nav-link link-secondary",
                                                            "Secondary link, no underline",
                                                        ),
                                                        (
                                                            "nav-link link-success",
                                                            "Success link, no underline",
                                                        ),
                                                        (
                                                            "nav-link link-danger",
                                                            "Danger link, no underline",
                                                        ),
                                                        (
                                                            "nav-link link-warning",
                                                            "Warning link, no underline",
                                                        ),
                                                        (
                                                            "nav-link link-info",
                                                            "Info link, no underline",
                                                        ),
                                                        (
                                                            "nav-link link-light",
                                                            "Light link, no underline",
                                                        ),
                                                        (
                                                            "nav-link link-dark",
                                                            "Dark link, no underline",
                                                        ),
                                                    ],
                                                    label="Post title item style",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "text_wrap",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("", "Text wrap"),
                                                        (
                                                            "text-nowrap",
                                                            "No text wrapping",
                                                        ),
                                                    ],
                                                    label="Text wrapping",
                                                    required=False,
                                                ),
                                            ),
                                            (
                                                "order_by",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("created_at", "Older first"),
                                                        ("-created_at", "Newer first"),
                                                        ("title", "By title acsending"),
                                                        (
                                                            "-title",
                                                            "By title descending",
                                                        ),
                                                        (
                                                            "owner__username",
                                                            "By author ascending",
                                                        ),
                                                        (
                                                            "-owner__username",
                                                            "By author descending",
                                                        ),
                                                    ],
                                                    label="Posts ordering",
                                                    required=False,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
