# Generated by Django 4.1.9 on 2023-05-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waggylabs", "0046_site_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="waggylabssettings",
            name="navbar_active_link_weight",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Default"),
                    ("fw-bold", "Bold"),
                    ("fw-bolder", "Bolder"),
                    ("fw-semibold", "Semibold"),
                    ("fw-medium", "Medium"),
                    ("fw-normal", "Normal"),
                    ("fw-light", "Light"),
                    ("fw-lighter", "Lighter"),
                ],
                default="",
                help_text="Specifies the font weigth for the navigation bar active links.",
                max_length=25,
                verbose_name="Navigation bar active link weight",
            ),
        ),
        migrations.AddField(
            model_name="waggylabssettings",
            name="navbar_link_weight",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Default"),
                    ("fw-bold", "Bold"),
                    ("fw-bolder", "Bolder"),
                    ("fw-semibold", "Semibold"),
                    ("fw-medium", "Medium"),
                    ("fw-normal", "Normal"),
                    ("fw-light", "Light"),
                    ("fw-lighter", "Lighter"),
                ],
                default="",
                help_text="Specifies the font weigth for the navigation bar links.",
                max_length=25,
                verbose_name="Navigation bar link weight",
            ),
        ),
        migrations.AlterField(
            model_name="waggylabssettings",
            name="navbar_active_link_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Specifies the color and opacity for the navigation bar active links. If nothing chosen, navigation bar link color is used if it was specified. Otherwise the default theme color is used.",
                max_length=25,
                verbose_name="Navigation bar active link color",
            ),
        ),
        migrations.AlterField(
            model_name="waggylabssettings",
            name="navbar_link_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Specifies the color and opacity for the navigation bar links. If none specified, the default theme color is used.",
                max_length=25,
                verbose_name="Navigation bar link color",
            ),
        ),
    ]
