# Generated by Django 4.1.9 on 2023-05-15 14:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("waggylabs", "0047_site_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="waggylabssettings",
            name="menu_allow_repeating_parents",
            field=models.BooleanField(
                blank=True,
                default=1,
                verbose_name="Repeat parent links in the dropdown submenus",
            ),
        ),
        migrations.AddField(
            model_name="waggylabssettings",
            name="menu_max_levels",
            field=models.IntegerField(
                default=1,
                help_text="Specifies how deep in the page hierarchy the menu must be rendered, i.e. what is the level of depth to render the dropdown submenus.",
                validators=[
                    django.core.validators.MinValueValidator(
                        1,
                        message="Maximum number of menu levels cannot be less than 1.",
                    )
                ],
                verbose_name="Maximum number of menu levels",
            ),
        ),
    ]
