# Generated by Django 4.0.5 on 2022-07-13 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
        ('wagtailimages', '0024_index_image_file_hash'),
        ('waggy_labs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaggyLabsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_slogan', models.CharField(blank=True, help_text='Phrase, that appears in navbar on the right to the brand image.', max_length=255, verbose_name='Slogan')),
                ('navbar_site_name', models.BooleanField(default=True, help_text='Indicates if title of the Waggy Labs site appears in navbar e.g., Page Title - Site Name.', verbose_name='Show site name in navbar')),
                ('navbar_site_name_alignment', models.CharField(choices=[('L', 'Before page title'), ('R', 'After page title')], default='R', help_text='The alignment of site name: before or after page title.', max_length=1)),
                ('navbar_image', models.ForeignKey(blank=True, help_text='Image, that appears in navbar.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Brand image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
