# Generated by Django 4.0.5 on 2022-07-27 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0024_index_image_file_hash'),
        ('waggy_labs', '0002_waggylabssettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waggylabssettings',
            options={'verbose_name': 'Current Site Settings'},
        ),
        migrations.RenameField(
            model_name='waggylabssettings',
            old_name='navbar_site_name_alignment',
            new_name='site_name_alignment',
        ),
        migrations.RenameField(
            model_name='waggylabssettings',
            old_name='navbar_slogan',
            new_name='site_slogan',
        ),
        migrations.RemoveField(
            model_name='waggylabssettings',
            name='navbar_image',
        ),
        migrations.RemoveField(
            model_name='waggylabssettings',
            name='navbar_site_name',
        ),
        migrations.AddField(
            model_name='waggylabssettings',
            name='show_site_name',
            field=models.BooleanField(default=True, help_text='Indicates if title of the Waggy Labs site appears in navigation bar and in browser tab e.g., Page Title - Site Name.', verbose_name='Show site name in navigation bar'),
        ),
        migrations.AddField(
            model_name='waggylabssettings',
            name='site_icon',
            field=models.ForeignKey(blank=True, help_text='Image that appears in navigation bar and in the browser tab.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Navigation bar and browser tab image'),
        ),
        migrations.AddField(
            model_name='waggylabssettings',
            name='site_name_separator',
            field=models.CharField(blank=True, help_text='Separator for site name e.g., Page Title - Site Name or Page Title : Site Name.', max_length=10, verbose_name='Separator for the site name'),
        ),
    ]
