# Generated by Django 4.0.5 on 2022-08-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggy_labs', '0005_alter_waggylabssettings_navbar_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waggylabssettings',
            name='navbar_placement',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('sticky-top', 'Sticky top')], default='', help_text='Navigation bar placement options: default, sticky-top or fixed-top. See Bootstrap documentation.', max_length=10),
        ),
        migrations.AlterField(
            model_name='waggylabssettings',
            name='navbar_theme',
            field=models.CharField(choices=[('bg-light', 'Light'), ('navbar-dark bg-primary', 'Primary'), ('navbar-dark bg-dark', 'Dark')], default='bg-light', help_text='Navigation bar theme: dark or light. Choice depends on the choice of the CSS Bootstrap theme.', max_length=25),
        ),
    ]
