# Generated by Django 4.0.5 on 2022-08-06 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggy_labs', '0007_waggylabssettings_navbar_menu_alignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waggylabssettings',
            options={'verbose_name': 'Site Settings'},
        ),
        migrations.AddField(
            model_name='waggylabssettings',
            name='github_name',
            field=models.CharField(blank=True, help_text='GitHub username.', max_length=255, verbose_name='GitHub username'),
        ),
        migrations.AddField(
            model_name='waggylabssettings',
            name='instagram_name',
            field=models.CharField(blank=True, help_text='Instagram username without domain name and @ symbol.', max_length=255, verbose_name='Instagram username without domain name and @ symbol'),
        ),
        migrations.AddField(
            model_name='waggylabssettings',
            name='twitter_name',
            field=models.CharField(blank=True, help_text='Twitter username without domain name and @ symbol.', max_length=255, verbose_name='Twitter username without @ symbol'),
        ),
        migrations.AddField(
            model_name='waggylabssettings',
            name='youtube_name',
            field=models.CharField(blank=True, help_text='Youtube channel name.', max_length=255, verbose_name='Youtube channel name'),
        ),
    ]
