# Generated by Django 4.0.5 on 2022-08-06 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waggy_labs', '0009_waggylabssettings_show_social_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waggylabssettings',
            name='github_name',
        ),
        migrations.RemoveField(
            model_name='waggylabssettings',
            name='instagram_name',
        ),
        migrations.RemoveField(
            model_name='waggylabssettings',
            name='show_social_names',
        ),
        migrations.RemoveField(
            model_name='waggylabssettings',
            name='twitter_name',
        ),
        migrations.RemoveField(
            model_name='waggylabssettings',
            name='youtube_name',
        ),
        migrations.CreateModel(
            name='WaggyLabsSettingsSocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(help_text='Title of the social network. For example, Instagram.', max_length=255, verbose_name='Title of the social network.')),
                ('username', models.CharField(help_text='Username for the social network.', max_length=255, verbose_name='Username for the social network')),
                ('icon', models.CharField(blank=True, help_text='Icon name from Font Awesome website. If left blank, title will used.', max_length=255, verbose_name='Icon name from Font Awesome website')),
                ('domain', models.CharField(blank=True, help_text='Doamin name for the social network. If left blank, "com" will be used.', max_length=5, verbose_name='Domain name for the social network')),
                ('link_text', models.CharField(choices=[('icon', 'Only social netwok icon'), ('title', 'Title of the social network'), ('username', 'Username in the social network')], default='icon', help_text='Choose how to display URLs to the social networks: only icons of the networks, icons and network titles or icons and usernames in the networks. Note that some icons may not be available according to the network title. Please check Font Awesome Icons for icon availability.', max_length=10, verbose_name='Social network display text')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='waggy_labs.waggylabssettings')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
