# Generated by Django 4.0.5 on 2022-08-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggy_labs', '0011_alter_waggylabssettingssociallinks_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waggylabssettingssociallinks',
            name='domain',
            field=models.CharField(blank=True, help_text='Domain name for the social network. If left blank, "com" will be used.', max_length=10, verbose_name='Domain name for the social network'),
        ),
    ]
