# Generated by Django 4.0.5 on 2022-08-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggy_labs', '0012_alter_waggylabssettingssociallinks_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='waggylabssettingssociallinks',
            name='username_prefix',
            field=models.CharField(blank=True, help_text='Additional prefix before the username if display username is selects. For example "@" for Twitter.', max_length=10, verbose_name='Prefix for the username'),
        ),
    ]
