# Generated by Django 4.0.5 on 2022-08-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waggy_labs', '0013_waggylabssettingssociallinks_username_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waggylabssettings',
            name='navbar_theme',
            field=models.CharField(blank=True, choices=[('', 'Light'), ('navbar-dark bg-primary', 'Primary'), ('navbar-dark bg-dark', 'Dark')], default='', help_text='Navigation bar theme: dark or light. Choice depends on the choice of the CSS Bootstrap theme.', max_length=25),
        ),
    ]
