# Generated by Django 4.0.5 on 2022-08-12 19:47

from django.db import migrations, models
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtailmarkdown.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('waggy_labs', '0014_alter_waggylabssettings_navbar_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full subtitle', required=True)), ('paragraph', wagtail.blocks.RichTextBlock(required=True)), ('pages', wagtail.blocks.PageChooserBlock(can_choose_root=True, required=True)), ('embed', wagtail.embeds.blocks.EmbedBlock(required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=True)), ('markdown', wagtailmarkdown.blocks.MarkdownBlock(icon='code', required=True))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='waggylabssettings',
            name='navbar_theme',
            field=models.CharField(blank=True, choices=[('', 'Light'), ('primary', 'Primary'), ('dark', 'Dark')], default='', help_text='Navigation bar theme: dark or light. Choice depends on the choice of the CSS Bootstrap theme.', max_length=25),
        ),
    ]
