# Generated by Django 4.0.5 on 2022-08-14 19:07

from django.db import migrations
import waggy_labs.blocks.mathjax_markdown_block
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('waggy_labs', '0015_alter_sitepage_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full subtitle', required=True)), ('paragraph', wagtail.blocks.RichTextBlock(required=True)), ('pages', wagtail.blocks.PageChooserBlock(can_choose_root=True, required=True)), ('embed', wagtail.embeds.blocks.EmbedBlock(required=True)), ('document', wagtail.documents.blocks.DocumentChooserBlock(required=True)), ('markdown', waggy_labs.blocks.mathjax_markdown_block.MathJaxMarkdownBlock(icon='code', required=True))], use_json_field=True),
        ),
    ]
