# Generated by Django 4.1.1 on 2022-10-01 20:42

from django.db import migrations
import waggy_labs.blocks.mathjax_markdown
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("waggy_labs", "0018_alter_sitepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.CharBlock(
                            form_classname="full subtitle", required=True
                        ),
                    ),
                    ("paragraph", wagtail.blocks.RichTextBlock(required=True)),
                    (
                        "blockquote",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "quote",
                                    wagtail.blocks.TextBlock(
                                        help_text="Quote text.", required=True, rows=3
                                    ),
                                ),
                                (
                                    "author",
                                    wagtail.blocks.CharBlock(
                                        help_text="Author of the quoted text.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "source",
                                    wagtail.blocks.CharBlock(
                                        help_text="Source of the quoted text.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "anchor",
                                    wagtail.blocks.CharBlock(
                                        help_text="Anchor link id for referencing in a Markdown block using #anchor.",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "pages",
                        wagtail.blocks.PageChooserBlock(
                            can_choose_root=True, required=True
                        ),
                    ),
                    ("embed", wagtail.embeds.blocks.EmbedBlock(required=True)),
                    (
                        "document",
                        wagtail.documents.blocks.DocumentChooserBlock(required=True),
                    ),
                    (
                        "markdown",
                        waggy_labs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                            icon="doc-full", required=True
                        ),
                    ),
                    (
                        "figure",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="Choose an image", required=True
                                    ),
                                ),
                                (
                                    "caption",
                                    waggy_labs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                                        help_text="Figure caption", required=True
                                    ),
                                ),
                                (
                                    "anchor",
                                    wagtail.blocks.CharBlock(
                                        help_text="Anchor link id for referencing in a Markdown block using #anchor.",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
