# Generated by Django 4.1.1 on 2022-10-23 21:05

from django.db import migrations
import waggy_labs.blocks.mathjax_markdown
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("waggy_labs", "0021_alter_sitepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sitepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "heading",
                        wagtail.blocks.CharBlock(
                            form_classname="full subtitle", required=True
                        ),
                    ),
                    (
                        "blockquote",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "quote",
                                    wagtail.blocks.TextBlock(
                                        help_text="Quote text.", required=True, rows=3
                                    ),
                                ),
                                (
                                    "author",
                                    wagtail.blocks.CharBlock(
                                        help_text="Author of the quoted text.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "source",
                                    wagtail.blocks.CharBlock(
                                        help_text="Source of the quoted text.",
                                        required=False,
                                    ),
                                ),
                                (
                                    "anchor",
                                    wagtail.blocks.CharBlock(
                                        help_text="Anchor link id for referencing in a Markdown block using #anchor.",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "pages",
                        wagtail.blocks.PageChooserBlock(
                            can_choose_root=True, required=True
                        ),
                    ),
                    ("embed", wagtail.embeds.blocks.EmbedBlock(required=True)),
                    (
                        "document",
                        wagtail.documents.blocks.DocumentChooserBlock(required=True),
                    ),
                    (
                        "markdown",
                        waggy_labs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                            icon="doc-full", required=True
                        ),
                    ),
                    (
                        "code",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "code",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "mode",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("python", "Python"),
                                                        ("clike", "C, C++, C#"),
                                                        ("clike", "Java"),
                                                        ("javascript", "Javascript"),
                                                        ("xml", "HTML, XML"),
                                                        ("octave", "MATLAB"),
                                                        ("mathematica", "Mathematica"),
                                                        ("r", "R"),
                                                        ("clike", "Kotlin"),
                                                        ("swift", "Swift"),
                                                        ("powershell", "Powershell"),
                                                        ("sql", "SQL"),
                                                        ("css", "CSS"),
                                                    ],
                                                    help_text="Choose the programming language.",
                                                ),
                                            ),
                                            (
                                                "code",
                                                wagtail.blocks.TextBlock(
                                                    help_text="Write or paste code.",
                                                    required=True,
                                                    rows=4,
                                                ),
                                            ),
                                        ]
                                    ),
                                ),
                                (
                                    "caption",
                                    waggy_labs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                                        easymde_max_height="200px",
                                        easymde_min_height="200px",
                                        easymde_toolbar_config="bold,italic,strikethrough,|,unordered-list,ordered-list,link,|,preview,side-by-side,fullscreen,guide",
                                        help_text="Listing caption",
                                        required=False,
                                    ),
                                ),
                                (
                                    "anchor",
                                    wagtail.blocks.CharBlock(
                                        help_text="Anchor link id for referencing in a Markdown block using #anchor.",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "figure",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        help_text="Choose an image", required=True
                                    ),
                                ),
                                (
                                    "caption",
                                    waggy_labs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                                        easymde_max_height="200px",
                                        easymde_min_height="200px",
                                        easymde_toolbar_config="bold,italic,strikethrough,|,unordered-list,ordered-list,link,|,preview,side-by-side,fullscreen,guide",
                                        help_text="Figure caption",
                                        required=False,
                                    ),
                                ),
                                (
                                    "anchor",
                                    wagtail.blocks.CharBlock(
                                        help_text="Anchor link id for referencing in a Markdown block using #anchor.",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "equation",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "equation",
                                    wagtail.blocks.TextBlock(
                                        help_text="Write or paste LaTeX style equation. If no \\begin{...} command is provided, \\begin{equation} and \\end{equation} will be added automatically.",
                                        required=True,
                                        rows=4,
                                    ),
                                ),
                                (
                                    "caption",
                                    waggy_labs.blocks.mathjax_markdown.MathJaxMarkdownBlock(
                                        easymde_max_height="200px",
                                        easymde_min_height="200px",
                                        easymde_toolbar_config="bold,italic,strikethrough,|,unordered-list,ordered-list,link,|,preview,side-by-side,fullscreen,guide",
                                        help_text="Equation caption",
                                        required=False,
                                    ),
                                ),
                                (
                                    "anchor",
                                    wagtail.blocks.CharBlock(
                                        help_text="Anchor link id for referencing in a Markdown block using #anchor. Ignored if \\label{...} is present.",
                                        max_length=50,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
